apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-to-https
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: eg
      sectionName: http  # The specific listener
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301  # Permanent redirect