apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: global-est
  namespace: {{ .Release.Namespace }}
  labels:
    auth: "public"
spec:
  parentRefs:
    - name: eg
      sectionName: https  # The specific listener
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /.well-known/est
      backendRefs:
        - name: dms-manager
          port: 8085