apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ui
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: eg
      sectionName: https  # The specific listener
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: ui
          port: 8080