apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: api-va
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: eg
      sectionName: http  # The specific listener
    - name: eg
      sectionName: https  # The specific listener
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /api/va/
      filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: "/"
      backendRefs:
        - name: va
          port: 8085
          