FROM quay.io/keycloak/keycloak:21.0.0
WORKDIR /opt/keycloak

ENV HOSTNAME_STRICT_HTTPS=false

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres

# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore

COPY ./themes/theme/lamassu.v2 /opt/keycloak/themes/lms-theme
COPY ./base-realm.json /opt/keycloak/data/import/base-realm.json

RUN /opt/keycloak/bin/kc.sh build
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]