FROM golang:1.19
WORKDIR /app
COPY . .
WORKDIR /app
ENV GOSUMDB=off
RUN go build -mod=vendor -o opa-rem-logger main.go 

# Alpine and scartch dont work for this image due to non corss compileable HSM library
FROM ubuntu:22.04
COPY --from=0 /app/opa-rem-logger /
CMD ["/opa-rem-logger"]
