FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    git \
    automake \
    autoconf \
    libtool \
    pkg-config \
    build-essential \
    libssl-dev \
    sqlite3 \
    libsqlite3-dev \
    cmake \
    libseccomp-dev

# Builging sfthsmv2/installing
RUN git clone https://github.com/opendnssec/SoftHSMv2.git && \
    cd SoftHSMv2 && \
    sh autogen.sh && \
    ./configure --disable-non-paged-memory --with-objectstore-backend-db && \
    make && \
    make install && \
    mkdir -p /softhsm/tokens
    # cp src/bin/util/softhsm2-util /usr/bin/ && \
    # mkdir -p /usr/local/lib/softhsm && \
    # cp -p src/lib/.libs/libsofthsm2.so /usr/local/lib/softhsm/libsofthsm2.so

# Install pkcs11-tool
RUN apt-get install -y opensc 

# building/installing pkcs11-proxy
RUN git clone https://github.com/SUNET/pkcs11-proxy && \
    cd pkcs11-proxy && \
    cmake . && make && make install && cp pkcs11-daemon /usr/local/bin/

COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh

EXPOSE 5657

# SoftHSM only logs into Syslog. We need to run a syslog daemon to capture the logs
RUN apt-get install syslog-ng -y

ENTRYPOINT  [ "/app/start.sh" ]